#!/bin/bash

ENV_ACCESS_KEY="${1}_ACCESS_KEY"
ENV_SECRET_KEY="${1}_SECRET_KEY"

if [ -z "${!ENV_ACCESS_KEY}" ]; then
  echo "Environment variable ${ENV_ACCESS_KEY} is not set"
  exit 1
fi

if [ -z "${!ENV_SECRET_KEY}" ]; then
  echo "Environment variable ${ENV_SECRET_KEY} is not set"
  exit 1
fi

cat > $HOME/.s3cfg << EOF
[default]
access_key = ${!ENV_ACCESS_KEY}
secret_key = ${!ENV_SECRET_KEY}
EOF
